import { jsPDF } from "jspdf";
import { fmtTimestamp } from "@/lib/api";

/**
 * Export a forecast/prediction result as a clean tabular PDF.
 * Works for both /predict and /future_predict responses.
 */
export function exportPredictionPDF(result, scenario, kind = "future") {
  if (!result) return;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 48;

  // Header
  doc.setFont("helvetica", "bold"); doc.setFontSize(16);
  doc.text("Network Digital Twin — " + (kind === "future" ? "Future Forecast" : "Current Prediction"), 48, y);
  y += 22;
  doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(110);
  doc.text(`Scenario: ${scenario}`, 48, y);
  doc.text(`Generated: ${fmtTimestamp(result.timestamp)}`, W - 48, y, { align: "right" });
  y += 14;
  doc.text(`Risk Level: ${result.risk_level}`, 48, y);
  if (kind === "future" && result.forecast_horizon) {
    doc.text(`Horizon: Next ${result.forecast_horizon} steps`, W - 48, y, { align: "right" });
  }
  y += 16;
  doc.setDrawColor(200); doc.line(48, y, W - 48, y); y += 18;

  // KPI table
  doc.setTextColor(20); doc.setFont("helvetica", "bold"); doc.setFontSize(11);
  doc.text("Predicted KPIs", 48, y); y += 14;

  const rows = kind === "future" ? [
    ["Latency", result.future_latency_ms, "ms"],
    ["Throughput", result.future_throughput_mbps, "Mbps"],
    ["Packet Loss", result.future_packet_loss_percent, "%"],
    ["Utilization", result.future_utilization_percent, "%"],
    ["Traffic Load", result.future_traffic_load_mbps, "Mbps"],
    ["Active Users", result.future_active_users, ""],
    ["Jitter", result.future_jitter_ms, "ms"],
    ["Queue Occupancy", result.future_queue_occupancy_percent, "%"],
  ] : [
    ["Latency", result.predicted_latency_ms, "ms"],
    ["Throughput", result.predicted_throughput_mbps, "Mbps"],
    ["Packet Loss", result.predicted_packet_loss_percent, "%"],
    ["Utilization", result.predicted_utilization_percent, "%"],
    ["Jitter", result.predicted_jitter_ms, "ms"],
    ["Queue Occupancy", result.predicted_queue_occupancy_percent, "%"],
  ];

  doc.setFont("helvetica", "normal"); doc.setFontSize(10);
  rows.forEach(([k, v, u]) => {
    doc.setTextColor(80); doc.text(k, 60, y);
    doc.setTextColor(20); doc.text(`${v ?? "—"} ${u}`, 260, y);
    y += 14;
  });

  // Scenario insight
  if (result.scenario_insight) {
    y += 8; doc.setDrawColor(220); doc.line(48, y, W - 48, y); y += 16;
    doc.setFont("helvetica", "bold"); doc.text("Scenario Insight", 48, y); y += 14;
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(result.scenario_insight, W - 96);
    doc.setTextColor(60); doc.text(lines, 48, y); y += lines.length * 12;
  }

  // Forecast summary
  if (result.forecast_summary?.length) {
    y += 8; doc.setDrawColor(220); doc.line(48, y, W - 48, y); y += 16;
    doc.setFont("helvetica", "bold"); doc.setTextColor(20); doc.text("AI Forecast Summary", 48, y); y += 14;
    doc.setFont("helvetica", "normal"); doc.setTextColor(60);
    result.forecast_summary.forEach((m) => {
      const lines = doc.splitTextToSize("• " + m, W - 96);
      doc.text(lines, 48, y); y += lines.length * 12 + 2;
    });
  }

  // Recommendations
  if (result.recommendations?.length) {
    y += 8; doc.setDrawColor(220); doc.line(48, y, W - 48, y); y += 16;
    doc.setFont("helvetica", "bold"); doc.setTextColor(20); doc.text("Recommendations", 48, y); y += 14;
    doc.setFont("helvetica", "normal"); doc.setTextColor(60);
    result.recommendations.forEach((r) => {
      const lines = doc.splitTextToSize("• " + r, W - 96);
      doc.text(lines, 48, y); y += lines.length * 12 + 2;
    });
  }

  // Footer
  doc.setTextColor(150); doc.setFontSize(8);
  doc.text("Generated by NetTwin · NOC.AI — Network Digital Twin", W / 2, doc.internal.pageSize.getHeight() - 24, { align: "center" });

  const stamp = (result.timestamp || "").replace(/[:.]/g, "-").slice(0, 19) || "report";
  doc.save(`nettwin-${kind}-${scenario}-${stamp}.pdf`);
}
